### ISSUE TITLE
more detailed instruction for neural response prediction

### ISSUE THREAD

**Issue by shanggao11** [MouseLand/facemap#152]
Hi 
Thanks for the tutorial, it is really helpful!! However, May I ask few questions about the neural response prediction part?
1. For neural data, the shape is (neuron number, time), in here, is the second dimension here the firing rate of the neurons? Does facemap have any requirement on the precision (like ms, seconds)? Cause it crashes when the data is very large 
2. for camera and neural timestamp, could you please explain more about it? 
it will be nice if you can provide some sample data! I tried to search on the tutorial, but I am having a hard time to find it :)
Thanks!

**Comment by Atika-Syeda** [comment]
Hi @shanggao11, thanks for your question. To answer them:
1. Yes, neural data is neurons x time. In our paper we used deconvolved spikes from calcium imaging but you can try firing rates. We used about 50,000 neurons data so the requirement will depend on your system's memory. You can try PC prediction instead of single neuron.
2. In our paper we collected behavioral and neural data at different sampling rates so if that's the case for your data then you  can provide the timestamp information for each variable so the code will resample behavior to neural timescale. You can find sample data here: https://janelia.figshare.com/articles/dataset/Facemap_a_framework_for_modeling_neural_activity_based_on_orofacial_tracking/23712957

Hope that helps!
